"""i deleted nullable in region_id in city table

Revision ID: 48701ea21f71
Revises: 6b2754452f60
Create Date: 2026-04-13 01:11:14.302558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48701ea21f71'
down_revision = '6b2754452f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
